/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 LapaRoja.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LapaRoja({ modelo, ...props }) {
  
    const { nodes, materials } = useGLTF(modelo);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lapa.geometry} material={materials['51']} />
    </group>
  )

}

