/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 LoraNucaAmarilla.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LoroNucaAmarilla({  ...props }) {
 
    const { nodes, materials } = useGLTF("/models/LoraNucaAmarilla.glb");
    return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LoraNucaAmarilla.geometry} material={materials.LoraNucaAmarilla} />
    </group>
  );
  
}


useGLTF.preload("/models/LoraNucaAmarilla.glb");