/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 LoraNucaAmarilla.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LoroNucaAmarilla({ modelo, ...props }) {
  if (modelo) {
    const { nodes, materials } = useGLTF(modelo);
    return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LoraNucaAmarilla.geometry} material={materials.LoraNucaAmarilla} />
    </group>
  );
    }
    return null;
}
