/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Saino.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Saino(props) {
  const { nodes, materials } = useGLTF('/models/Saino.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Saino.geometry} material={materials.CollaredPeccary_mat} />
    </group>
  )
}

useGLTF.preload('/models/Saino.gltf')
