/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 TortugaNegra.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TortugaNegra({  ...props }) {
  
    const { nodes, materials } = useGLTF("/models/TortugaNegra.gltf");
    return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TortugaNegra.geometry} material={materials['13102_pondturtle']} />
    </group>
  );
  
}
