/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 TortugaRoja.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TortugaRoja(props) {
  const { nodes, materials } = useGLTF('/models/TortugaRoja.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TortugaRoja.geometry} material={materials.TortugaRoja} />
    </group>
  )
}

useGLTF.preload('/models/TortugaRoja.gltf')
