/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Toucan.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Toucan.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bird_Toucan.geometry} material={materials.Bird_Toucan} />
    </group>
  )
}

useGLTF.preload('/Toucan.glb')
