/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Chucuyo.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chucuyo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LoraCopeteRojo002.geometry} material={materials.Chucuyo} />
      <mesh geometry={nodes.LoraCopeteRojo002_1.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/Chucuyo.glb')
